swagger: "2.0"
info:
  version: 1.0.0
  title: laura_teste
  description: Aplicação desenvolvida para o teste prátido para a vaga de desenvolvedor backend.
basePath: /api
tags:
  - name: Estudantes
    description: API para gerenciamento dos estudantes
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  EstudanteBody:
    type: object
    title: estudante
    properties:
      nome:
        type: string
        example: ADALTO SEBASTIAO DA SILVA JUNIOR
      idade_ate_31_12_2016:
        type: number
        example: 18
      ra:
        type: number
        example: 8570
      campus:
        type: string
        example: AQ
      municipio:
        type: string
        example:  Aquidauana
      curso:
        type: string
        example: TÉCNICO EM INFORMÁTICA
      modalidade:
        type: string
        example: PRESENCIAL
      nivel_do_curso:
        type: string
        example: SUBSEQUENTE
      data_inicio:
        type: string
        example: 2015-07-27

  totalAlunosBody:
    type: object
    title: estudante
    properties:
      campus:
        type: string
        example: DR      
      data_inicio:
        type: string
        example: 2013-01-01
      data_fim:
        type: string
        example: 2016-01-01

  deletarBody:
    type: object
    title: estudante
    properties:
      campus:
        type: string
        example: AQ 
      ra:
        type: number
        example: 8570
         
      

paths:
  /database/popular:
    post:
      tags:
        - Database
      description: Popula a base de dados com o arquivo csv
      responses:
        200:
          description: Sucesso

  /estudantes:
    get:
      tags:
        - Estudantes
      description: Retorna todos os estudantes na base de dados sem ordenação.
      responses:
        200:
          description: Retorna todos os estudantes na base de dados sem ordenação.
  
  /estudantes/novo:
    post:
      tags:
        - Estudantes
      description: Insere um novo estudante.
      parameters:
        - name: Estudantes
          in: body
          description: um estudante
          required: true
          schema: 
            $ref: "#/definitions/EstudanteBody"
      responses:
        200:
          description: Retorna o estudante inserido

  /estudantes/listarModalidade/{modalidade}/{data_inicio}/{data_fim}:
    get:
      tags:
        - Estudantes
      description: Retorna todos os itens de uma modalidade em um período ordenados por data.
      parameters:
        - name: modalidade
          in: path
          required: true
          description: A modalidade a ser buscada.
          type: string
        - name: data_inicio
          in: path
          required: true
          description: A data inicial da busca (YYYY-MM-DD).
          type: string
        - name: data_fim
          in: path
          required: true
          description: A data final da busca (YYYY-MM-DD).
          type: string
      responses:
        200:
          description: Retorna todos os itens de uma modalidade em um período ordenados por data.
        404:
          description: Sem resultado para o filtro.

  /estudantes/listarCursos/{campus}:
    get:
      tags:
        - Estudantes
      description: Retorna todos os cursos de um campus.
      parameters:
        - name: campus
          in: path
          required: true
          description: O campus a ser buscado.
          type: string
      responses:
        200:
          description: Retorna todos os cursos de um campus.

  /estudantes/totalAlunos:
    post:
      tags:
        - Estudantes
      description: Retorna o número total de alunos num campus em um dado período.
      parameters:
        - name: Estudantes
          in: body
          description: um estudante
          required: true
          schema: 
            $ref: "#/definitions/totalAlunosBody"
      responses:
        200:
          description: Retorna o número total de alunos num campus em um dado período.

  /estudantes/buscarAluno/{ra}:
    get:
      tags:
        - Estudantes
      parameters:
        - name: ra
          in: path
          required: true
          description: O RA do estudante a ser buscado.
          type: integer
      responses:
        200:
          description: Retorna o estudante encontrado.
        404:
          description: Estudante não encontrado.         
  
  /estudantes/{id}:
    get:
      tags:
        - Estudantes
      parameters:
        - name: id
          in: path
          required: true
          description: O id do estudante a ser buscado
          type: integer
      responses:
        200:
          description: Retorna o estudante encontrado
        404:
          description: Estudante não encontrado

  /estudantes/deletar:
    delete:
      tags:
        - Estudantes
      description: Retorna o número total de alunos num campus em um dado período.
      parameters:
        - name: Estudantes
          in: body
          description: um estudante
          required: true
          schema: 
            $ref: "#/definitions/deletarBody"
      responses:
        200:
          description: Retorna o número total de alunos num campus em um dado período.

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification